[package]
name = "raftd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raftd"
path = "src/bin/main.rs"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
clap = { version = "4.5.23", features = ["derive", "env"] }
futures = "0.3.31"
openraft = { path = "../openraft/openraft", features = ["serde", "type-alias"] }
prost = "0.13.4"
rocksdb = "0.23.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", default-features = false, features = ["sync"] }
tonic = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
prost-build = "0.13.4"
tonic-build = "0.12.3"
