[package]
name = "raftd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raftd"
path = "src/bin/main.rs"

[[bin]]
name = "raft"
path = "src/bin/client.rs"

[features]
default = ["rhai", "aws"]
static = []
rhai = ["dep:rhai"]
aws = ["dep:aws-sdk-ec2", "dep:aws-config"]

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
config = "0.15.4"
futures = "0.3.31"
openraft = { path = "./openraft/openraft", features = ["type-alias"] }
prost = "0.13.4"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", default-features = false, features = ["sync"] }
tonic = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
http = { version = "1" }
rhai = { version = "1.21.0", optional = true, features = ["sync"] }
aws-sdk-ec2 = { version = "1.118.0", optional = true }
aws-config = { version = "1.6.0", optional = true }

[build-dependencies]
prost-build = "0.13.4"
tonic-build = "0.12.3"
