FROM messense/rust-musl-cross:aarch64-musl AS base
USER root

FROM base

WORKDIR /
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
RUN mv bazel-archive-keyring.gpg /usr/share/keyrings && \
  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" \
    | tee /etc/apt/sources.list.d/bazel.list
RUN apt update && apt install -y bazel

WORKDIR /
RUN curl -L -J -O https://github.com/protocolbuffers/protobuf/archive/refs/tags/v29.3.tar.gz
RUN tar -xzf protobuf-29.3.tar.gz
RUN git clone --single-branch --depth=1 https://github.com/lz4/lz4.git
RUN git clone --single-branch --depth=1 https://github.com/facebook/zstd.git

WORKDIR /lz4
RUN make install

WORKDIR /zstd
RUN make install

WORKDIR /protobuf-29.3
RUN bazel build --enable_bzlmod :protoc :protobuf
RUN cp bazel-bin/protoc /usr/local/bin
RUN mkdir -p /usr/local/include
RUN cp -r src/google /usr/local/include/
