FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge AS base

WORKDIR /

RUN apt update && apt install -y \
  apt-transport-https \
  curl \
  gnupg \
  protobuf-compiler \
  build-essential \
  cmake \
  perl \
  git \
  pkg-config \
  libsnappy-dev \
  zlib1g-dev \
  liblz4-dev \
  libzstd-dev \
  libtool \
  autoconf \
  libgflags-dev \
  clang \
  libclang-dev \
  ninja-build \
  python3

RUN echo "hi"
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
RUN mv bazel-archive-keyring.gpg /usr/share/keyrings && \
  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" \
    | tee /etc/apt/sources.list.d/bazel.list

RUN apt update && apt install -y bazel

RUN git clone --single-branch --depth=1 https://github.com/llvm/llvm-project.git

WORKDIR /llvm-project

RUN cmake -S llvm -B build -G Ninja \
  -DLLVM_ENABLE_PROJECTS="clang;lld" \
  -DLIBCLANG_BUILD_STATIC=ON \
  -DLLVM_TARGETS_TO_BUILD=AArch64 \
  -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-unknown-linux-gnu \
  -DCMAKE_BUILD_TYPE=Release
RUN ninja -C build install

WORKDIR /

FROM base

RUN curl -L -J -O https://github.com/protocolbuffers/protobuf/archive/refs/tags/v29.3.tar.gz
RUN tar -xzf protobuf-29.3.tar.gz
RUN git clone --single-branch --depth=1 https://github.com/lz4/lz4.git
RUN git clone --single-branch --depth=1 https://github.com/facebook/zstd.git

WORKDIR /lz4
RUN make CC=aarch64-linux-gnu-gcc AR=aarch64-linux-gnu-ar
RUN make install

WORKDIR /zstd
RUN make CC=aarch64-linux-gnu-gcc AR=aarch64-linux-gnu-ar
RUN make install

WORKDIR /protobuf-29.3
RUN bazel build --enable_bzlmod :protoc :protobuf
RUN cp bazel-bin/protoc /usr/local/bin
