[package]
name = "disco-common"
readme = "../README.md"

version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
categories    = { workspace = true }
description   = { workspace = true }
documentation = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }

[features]
default = ["aws"]
static = []
aws = ["dep:aws-sdk-ec2", "dep:aws-config"]

[dependencies]
clap               = { workspace = true }
config             = { workspace = true }
futures            = { workspace = true }
openraft           = { workspace = true }
prost              = { workspace = true }
serde              = { workspace = true }
tokio              = { workspace = true }
tonic              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
http               = { workspace = true }
rhai               = { workspace = true }
aws-sdk-ec2        = { workspace = true, optional = true }
aws-config         = { workspace = true, optional = true }
